from typing import Any, Mapping

from Component.Accessor import AccessorComponent, AccessorTypeComponent
from Component.Component import Component
from Component.Dataminer import (
    AbstractDataminerCollectionComponent,
    CoverageDataminerCollectionComponent,
    DataminerCollectionComponent,
    DataminerSettingsComponent,
)
from Component.Log import LogComponent
from Component.Serializer import SerializerComponent
from Component.Structure import (
    BranchlessStructureComponent,
    CacheStructureComponent,
    ConditionStructureComponent,
    ConvergingStructureComponent,
    DelegateComponent,
    DictStructureComponent,
    FileStructureComponent,
    FilterComponent,
    FunctionComponent,
    IterableStructureComponent,
    KeyComponent,
    KeymapStructureComponent,
    MappingStructureComponent,
    NormalizerStructureComponent,
    NumberStructureComponent,
    PassthroughStructureComponent,
    PrimitiveStructureComponent,
    SequenceStructureComponent,
    StringStructureComponent,
    StructureBaseComponent,
    StructureComponent,
    StructureTagComponent,
    SwitchStructureComponent,
    UnionStructureComponent,
    WithinStructureComponent,
)
from Component.Tablifier import TablifierComponent
from Component.Version import (
    VersionComponent,
    VersionFileComponent,
    VersionFileTypeComponent,
    VersionProviderComponent,
)
from Component.VersionTag import (
    LatestSlotComponent,
    RangeVersionTagAutoAssignerComponent,
    VersionTagAutoAssignerComponent,
    VersionTagComponent,
    VersionTagOrderComponent,
)

component_types_dict:Mapping[str,type["Component[Any, Any]"]] = {component_type.type_name: component_type for component_type in (
    AbstractDataminerCollectionComponent.AbstractDataminerCollectionComponent,
    AccessorComponent.AccessorComponent,
    AccessorTypeComponent.AccessorTypeComponent,
    VersionTagOrderComponent.AllowedChildrenComponent,
    FilterComponent.AndFilterComponent,
    BranchlessStructureComponent.BranchlessStructureComponent,
    CacheStructureComponent.CacheStructureComponent,
    ConditionStructureComponent.ConditionStructureComponent,
    ConvergingStructureComponent.ConvergingStructureComponent,
    CoverageDataminerCollectionComponent.CoverageDataminerCollectionComponent,
    DataminerCollectionComponent.DataminerCollectionComponent,
    DataminerSettingsComponent.DataminerSettingsComponent,
    DelegateComponent.DelegateComponent,
    DictStructureComponent.DictStructureComponent,
    FilterComponent.EqFilterComponent,
    FileStructureComponent.FileStructureComponent,
    FilterComponent.FilterComponent,
    FunctionComponent.FunctionComponent,
    FilterComponent.GeFilterComponent,
    FilterComponent.GtFilterComponent,
    IterableStructureComponent.IterableStructureComponent,
    KeyComponent.KeyComponent,
    FilterComponent.KeyFilterComponent,
    KeymapStructureComponent.KeymapStructureComponent,
    FilterComponent.KeyNotPresentFilterComponent,
    FilterComponent.KeyPresentFilterComponent,
    LatestSlotComponent.LatestSlotComponent,
    FilterComponent.LeFilterComponent,
    FilterComponent.LtFilterComponent,
    LogComponent.LogComponent,
    MappingStructureComponent.MappingStructureComponent,
    FilterComponent.MetaFilterComponent,
    FilterComponent.NeFilterComponent,
    NormalizerStructureComponent.NormalizerStructureComponent,
    NumberStructureComponent.NumberStructureComponent,
    FilterComponent.OrFilterComponent,
    FilterComponent.NandFilterComponent,
    FilterComponent.NorFilterComponent,
    PassthroughStructureComponent.PassthroughStructureComponent,
    PrimitiveStructureComponent.PrimitiveStructureComponent,
    RangeVersionTagAutoAssignerComponent.RangeVersionTagAutoAssignerComponent,
    SequenceStructureComponent.SequenceStructureComponent,
    SerializerComponent.SerializerComponent,
    StringStructureComponent.StringStructureComponent,
    StructureComponent.StructureComponent,
    StructureBaseComponent.StructureBaseComponent,
    StructureTagComponent.StructureTagComponent,
    SwitchStructureComponent.SwitchStructureComponent,
    TablifierComponent.TablifierComponent,
    UnionStructureComponent.UnionStructureComponent,
    FilterComponent.ValueFilterComponent,
    VersionComponent.VersionComponent,
    VersionFileComponent.VersionFileComponent,
    VersionFileTypeComponent.VersionFileTypeComponent,
    VersionProviderComponent.VersionProviderComponent,
    VersionTagComponent.VersionTagComponent,
    VersionTagAutoAssignerComponent.VersionTagAutoAssignerComponent,
    VersionTagOrderComponent.VersionTagOrderComponent,
    WithinStructureComponent.WithinStructureComponent,
)}
